package com.mercur.upgrade.e2e;

import org.junit.jupiter.api.extension.AfterAllCallback;
import org.junit.jupiter.api.extension.BeforeEachCallback;
import org.junit.jupiter.api.extension.ExtensionContext;
import org.junit.jupiter.api.extension.TestWatcher;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Writes the results of a test class and its @Nested groups to test-results/corner-cases.md: one table per group, one
 * row per test with PASS/FAIL and what was observed. A test states what it observed with {@link #observe}; for a
 * failure, the assertion message is used when nothing was observed. Overwritten on every run.
 */
final class MarkdownReport implements BeforeEachCallback, TestWatcher, AfterAllCallback {

    static final Path FILE = Path.of("test-results", "corner-cases.md");

    private static final Map<String, List<String[]>> groups = new LinkedHashMap<>();
    private static String observed = "";

    /** What the running test saw (status, record, count...), shown in its row. */
    static void observe(String text) {
        observed = text;
    }

    @Override
    public void beforeEach(ExtensionContext context) {
        observed = "";
    }

    @Override
    public void testSuccessful(ExtensionContext context) {
        add(context, "PASS", observed);
    }

    @Override
    public void testFailed(ExtensionContext context, Throwable cause) {
        add(context, "**FAIL**", observed.isEmpty() ? String.valueOf(cause.getMessage()) : observed);
    }

    @Override
    public void testAborted(ExtensionContext context, Throwable cause) {
        add(context, "SKIPPED", String.valueOf(cause.getMessage()));
    }

    /** Once, after the outermost class: the extension is inherited by the @Nested groups. */
    @Override
    public void afterAll(ExtensionContext context) throws IOException {
        if (context.getRequiredTestClass().getEnclosingClass() != null) {
            return;
        }
        long passed = groups.values().stream().flatMap(List::stream).filter(row -> row[1].equals("PASS")).count();
        long total = groups.values().stream().mapToLong(List::size).sum();
        StringBuilder md = new StringBuilder()
                .append("# Corner-case results (latest run)\n\n")
                .append("Generated by `CornerCasesTest` (`account-upgrade-e2e`, `mvnw verify -Pcorner-cases`) and overwritten ")
                .append("on every run.\n\n")
                .append("- **Run at:** ").append(ZonedDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss xxx")))
                .append('\n')
                .append("- **Target:** ").append(E2eSettings.API_URL).append(" (namespace `").append(E2eSettings.NAMESPACE)
                .append("`)\n")
                .append("- **Result:** ").append(passed == total ? "ALL PASS" : "FAILURES").append(": ")
                .append(passed).append(" passed, ").append(total - passed).append(" not passed, ").append(total)
                .append(" total\n");
        groups.forEach((group, rows) -> {
            md.append("\n## ").append(group).append("\n\n| Case | Result | Observed |\n|---|---|---|\n");
            for (String[] row : rows) {
                md.append("| ").append(cell(row[0])).append(" | ").append(row[1]).append(" | ").append(cell(row[2]))
                        .append(" |\n");
            }
        });
        Files.createDirectories(FILE.getParent());
        Files.writeString(FILE, md.toString());
        System.out.println("Results written to " + FILE.toAbsolutePath());
        groups.clear();
    }

    private static void add(ExtensionContext context, String result, String detail) {
        String group = context.getParent().flatMap(MarkdownReport::groupName).orElse("Other");
        groups.computeIfAbsent(group, name -> new ArrayList<>()).add(new String[] {context.getDisplayName(), result, detail});
    }

    // A parameterized test's invocation sits under its method; the group is the class above.
    private static Optional<String> groupName(ExtensionContext context) {
        return context.getTestMethod().isPresent()
                ? context.getParent().flatMap(MarkdownReport::groupName)
                : Optional.of(context.getDisplayName());
    }

    private static String cell(String text) {
        String flat = text.replaceAll("\\s+", " ").replace("|", "\\|").strip();
        return flat.length() > 180 ? flat.substring(0, 180) + "..." : flat;
    }
}
